### ISSUE TITLE
Why Harfbuzz

### ISSUE THREAD

**Issue by pigking12345** [nasser/harfbuzz-js-demo#1]
Hi Ramsey, this demo is amazing. I have some confusion about the harfbuzz part: why it is necessary? I found opentype.js is very powerful. Do you think harfbuzz is still a requirement to display text on three.js now?

**Comment by nasser** [comment]
harfbuzz (or something like it) is unavoidable for many non-Latin scripts, particularly Arabic. read this article for the context behind this repository: https://increment.com/programming-languages/unplain-text-primer-on-non-latin/

**Comment by pigking12345** [comment]
Thanks @nasser for the information!
